# Generated by Django 3.0.7 on 2020-06-30 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('purchaseDate', models.DateField()),
                ('miles', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Service Date')),
                ('service', models.CharField(choices=[('T', 'Tune Up'), ('P', 'Tire Pressure Check'), ('C', 'Chain Clean and Grease'), ('R', 'Repair')], default='T', max_length=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main_app.Bike')),
            ],
        ),
    ]
